<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GestaoDeTarefas.Domain\GestaoDeTarefas.Domain.csproj" />
    <ProjectReference Include="..\GestaoDeTarefas.Infrastructure\GestaoDeTarefas.Infrastructure.csproj" />
  </ItemGroup>

</Project>
